use makepad_widgets::*;

live_design! {
    SI_DEFAULT = #D4D4D8
    SI_PRIMARY = #006FEE
    SI_SECONDARY = #7828C8
    SI_SUCCESS = #17C964
    SI_WARNING = #F5A524
    SI_DANGER = #F31260
    SI_HOVER_OPACITY = 0.8
    // SI_HOVER_PRIMARY = (mix(SI_PRIMARY, SI_PRIMARY_H, 1.0 - SI_HOVER_OPACITY))
}