use makepad_widgets::*;

live_design! {
    SI_DEFAULT = #D4D4D8
    SI_PRIMARY = #006FEE
    SI_SECONDARY = #7828C8
    SI_SUCCESS = #17C964
    SI_WARNING = #F5A524
    SI_DANGER = #F31260
    SI_HOVER_OPACITY = 0.8
    // SI_HOVER_PRIMARY = (mix(SI_PRIMARY, SI_PRIMARY_H, 1.0 - SI_HOVER_OPACITY))

    SI_RADIUS_FULL = 10.0
    SI_RADIUS_LARGE = 8.0
    SI_RADIUS_MEDIUM = 6.0
    SI_RADIUS_SMALL = 4.0
    SI_RADIUS_NONE = 1.0
}